# Base Docker Compose File. We assume usage of redis by most (all) APIs due to usage of OAuth by all services
# We also assume MySQL usage in our code.
version: '3'
services:
    redis:
        container_name: transactionloggerservice_redis
        image: redis
        ports:
            - "6379"
        networks:
            - main_network
    database:
        container_name: transactionloggerservice_mysql
        image: mysql:8.0
        ports:
            - "3307:3306"
        expose:
            - "3307"
        environment:
            MYSQL_USER: "transactionloggerservice"
            MYSQL_PASSWORD: "transactionloggerservice"
            MYSQL_DATABASE: "transactionloggerservice"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

        networks:
            - main_network
    rabbitmq:
        image: rabbitmq:3.9.7-management-alpine
        volumes:
            - rabbit_data:/var/lib/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - backend
    adminer:
        image: adminer
        container_name: transactionloggerservice_mysql_client_web
        restart: always
        ports:
            - 10000:8080
        networks:
            - main_network
networks:
    main_network:
        driver: bridge
